### ISSUE TITLE
Using "extraVolumeMounts" in MDCB component causes an error converting YAML to JSON

### ISSUE THREAD

**Issue by chaich-pcs** [TykTechnologies/tyk-charts#392]
In my values YAML file, under the "tyk-mdcb" section, I tried to mount an extra volume like so:

```
    extraVolumes:
    - name: secrets-store-controlplane-tls
      csi: *controlplane-tls-secret-provider
    extraVolumeMounts:
    - name: secrets-store-controlplane-tls
      mountPath: /tmp/controlplane-tls
      readOnly: true
```

I try to do a "helm install --dry-run" and I get the following error.
**Error: INSTALLATION FAILED: YAML parse error on tyk-control-plane/charts/tyk-mdcb/templates/deployment-mdcb.yaml: error converting YAML to JSON: yaml: line 75: did not find expected key**

When I changed the code to the below (removing the "extraVolumeMounts" section), I don't get the error:
```
    extraVolumes:
    - name: secrets-store-controlplane-tls
      csi: *controlplane-tls-secret-provider
```

I tested using version 2.2.0 of the Helm chart.
