### ISSUE TITLE
Redis Sentinel configuration does not take effect in MDCB

### ISSUE THREAD

**Issue by chaich-pcs** [TykTechnologies/tyk-charts#395]
Even though Helm charts allow us to set the details of the Redis Sentinel configuration, it does not use it for MDCB.

For example, given the following configuration, "sentinelPass" and "masterName" is not used to create the MDCB pods.
```

global:
  redis:
    addrs:
      - db1.acme.com:26379
      - db2.acme.com:26379
      - db3.acme.com:26379
    enableSentinel: true
    sentinelPass: "abcdefg"
    masterName: "mymaster"
```

Instead, we have to populate it through the "extraEnvs" field like so
```
    extraEnvs:
    - name: TYK_MDCB_STORAGE_MASTERNAME
      value: mymaster
    - name: TYK_MDCB_STORAGE_SENTINELPASSWORD
      value: abcdefg
```

This is similar to this Github issue https://github.com/TykTechnologies/tyk-charts/issues/373
This is confusing as well as a duplicate effort.
It is also related to this issue, as setting the password this way is not usually considered secure.
https://github.com/TykTechnologies/tyk-charts/issues/374
